# Created by Thomas for 5.6.2

directory=/usr/share/zsh/scripts/zplug/init.zsh

# Install zplug if necessary
if [[ ! -f $directory ]]; then
    echo '\033[0;31m'zplug not installed!'\033[0m'
    echo Starting install:
    yay -Sy zplug --noconfirm
fi

source $directory

# Auto-update
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Plugins 
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/docker",   from:oh-my-zsh
zplug "plugins/docker-compose",   from:oh-my-zsh
zplug "plugins/command-not-found",   from:oh-my-zsh
zplug "plugins/colored-man-pages",   from:oh-my-zsh
zplug "plugins/taskwarrior",   from:oh-my-zsh
zplug "plugins/rand-quote",   from:oh-my-zsh
zplug "robbyrussell/oh-my-zsh",   use:lib/history.zsh, from:github, as:plugin
zplug "MichaelAquilina/zsh-you-should-use"

# Theme
zplug "geometry-zsh/geometry"
GEOMETRY_PROMPT_PREFIX=""

# Install packages that have not been installed yet
if ! zplug check --verbose; then
    zplug install
fi

zplug load # --verbose to see loaded modules

# Neovim alias
alias nv=nvim

# Tab highlighting
zstyle ':completion:*' menu select
# Color tab highlighting
eval "$(dircolors)"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Color the ls output and sort by directory
alias ls='ls --color=auto --group-directories-first'

# Enable fuzzy searching
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Transmission alias
trdown()
{
    for tor_file in ~/torrents/tor_queue/*; do
        transmission-remote -a $tor_file
    done
}
alias trstart="transmission-daemon"
alias trstop="pkill -f transmission-da"
alias trst="transmission-remote -l"
alias trcheck="ps -e | grep transmission"
alias watch="watch "

# history search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down


